Substitution of tomcat package name

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -40,6 +40,17 @@ fi
 
 if [ -z "${1}" -o "${1}" == "rpm" ] ; then
 
+    DISTROMV=`grep -Eo '[0-9]\.' /etc/redhat-release`
+    if [ "x${DISTROMV}" == "x5." ]; then
+        TOMCATPKG="tomcat5"
+    else if [ "x${DISTROMV}" == "x6." ]; then
+        TOMCATPKG="tomcat6"
+    else
+        echo "Cannot detect distro version"
+        exit 1
+    fi
+    fi
+
     mkdir -p  rpmbuild/RPMS
     mkdir -p  rpmbuild/SRPMS/
     mkdir -p  rpmbuild/SPECS/
@@ -60,6 +71,7 @@ if [ -z "${1}" -o "${1}" == "rpm" ] ; then
         sed -e 's|@PKGNAME@|'${PKGNAME}'|g' \
             -e 's|@PKGVERSION@|'${PKGVER}'|g' \
             -e 's|@PKGRELEASE@|'${PKGREL}'|g' \
+            -e 's|@TOMCATPKG@|'${TOMCATPKG}'|g' \
             project/${PKGNAME}.spec.in > rpmbuild/SPECS/${PKGNAME}.spec
         rpmbuild -ba --define "_topdir ${PWD}/rpmbuild" rpmbuild/SPECS/${PKGNAME}.spec
         
